POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImluIHllYXIgMzAwMCIsImlkIjoiNWZmNzhjNWI5NmM1M2ZiYmUwNTYxMzcwIiwiaWF0IjoxNjEwMDU5MTg5fQ.ILScC36agCM_pe72DR8ZIDvYJ1S9v9Al9mA-CuKIIxs

{
    "username": "ir",
    "name": "Tony Stark",
    "password": "salasana"
}